/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Audio.java
 *
 * Created on Jul 2, 2011, 12:41:27 AM
 */
package vpower.gui;

import audioanalyzer.AudioAnalyzerException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import vpower.engine.AudioRecorder;
import vpower.engine.DatabaseHandler;
import vpower.engine.VowelMatcher;

/**
 *
 * @author ninu
 */
public class Audio extends javax.swing.JPanel {
    private DatabaseHandler handler;
    private UI gui;
    private AudioRecorder rec;
    private VowelMatcher matcher;
    
    
    /** Creates new form Audio */
    public Audio(DatabaseHandler handler, UI gui) {
        initComponents();
        this.handler = handler;
        this.gui = gui;
        this.rec = new AudioRecorder();
        this.matcher = new VowelMatcher(handler.getDatabase());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        record_button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        add_to_db_radio = new javax.swing.JRadioButton();
        recognize_radio = new javax.swing.JRadioButton();
        vocala_text = new javax.swing.JTextField();
        recognize_button = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        record_button.setText("Record");
        record_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                record_buttonActionPerformed(evt);
            }
        });

        jLabel1.setText("Operation :");

        add_to_db_radio.setText("Add to Database");
        add_to_db_radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_to_db_radioActionPerformed(evt);
            }
        });

        recognize_radio.setText("Recognize");
        recognize_radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recognize_radioActionPerformed(evt);
            }
        });

        vocala_text.setFont(new java.awt.Font("Ubuntu", 0, 36));
        vocala_text.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        recognize_button.setText("Add");
        recognize_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recognize_buttonActionPerformed(evt);
            }
        });

        jLabel2.setText("Vowel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(record_button, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(recognize_radio)
                            .addComponent(add_to_db_radio)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vocala_text, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(recognize_button)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(record_button)
                    .addComponent(jLabel1)
                    .addComponent(add_to_db_radio))
                .addGap(1, 1, 1)
                .addComponent(recognize_radio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vocala_text, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(recognize_button)
                    .addComponent(jLabel2))
                .addContainerGap(28, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void add_to_db_radioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_to_db_radioActionPerformed
        recognize_radio.setSelected(false);
        vocala_text.setEditable(true);
        recognize_button.setText("Add");
    }//GEN-LAST:event_add_to_db_radioActionPerformed

    private void recognize_radioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recognize_radioActionPerformed
        add_to_db_radio.setSelected(false);
        vocala_text.setEditable(false);
        vocala_text.setText("");
        recognize_button.setText("Recognize");
    }//GEN-LAST:event_recognize_radioActionPerformed

    private void record_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_record_buttonActionPerformed
        if (record_button.getText().equalsIgnoreCase("Record")) {
            if (recognize_radio.isSelected()) {
                vocala_text.setText("");
            }
            record_button.setText("Stop");
            try {
                rec.start();
            }
            catch (LineUnavailableException ex) {
                System.err.println("Can`t start recording : " + ex);
                System.exit(1);
            }
        }
        else {
            record_button.setText("Record");
            rec.stop(); 
            try {
                if (rec.getWavFile().getSamples().isEmpty()) {
                    System.out.println("Not enough data in the recorded sound");
                }
                else {
                    System.out.println("Data recorded");
                }
            }
            catch (Exception ex) { }
        }
        
    }//GEN-LAST:event_record_buttonActionPerformed

    private void recognize_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recognize_buttonActionPerformed
        if (recognize_button.getText().equalsIgnoreCase("Add")) {
            String val = vocala_text.getText();

            if (val.length() != 1) {
                System.out.println("Must specify vowel");
            }
            else if (!(val.equalsIgnoreCase("A") || val.equalsIgnoreCase("E") || 
                    val.equalsIgnoreCase("I") || val.equalsIgnoreCase("O") || 
                    val.equalsIgnoreCase("U") )) {
                System.out.println("Must specify vowel");
            }
            else {
                val = val.toUpperCase();
                try {
                    handler.addWav(rec.getWavFile(), val, (String)this.gui.users.username_combo.getSelectedItem());
                } catch (Exception ex) {
                    System.err.println("Error at updating the Database : " + ex);
                }
            }
        }
        else {
            (new Thread() {
                @Override
                public void run() {
                    String val = null;
                    try {
                        val = matcher.match(rec.getWavFile(), (String)gui.users.username_combo.getSelectedItem());
                    } 
                    catch (Exception ex) {
                        System.err.println("Error matching the vowel : " + ex);
                    }
                    vocala_text.setText(val);
                }
            }).start();
        }
    }//GEN-LAST:event_recognize_buttonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JRadioButton add_to_db_radio;
    javax.swing.JLabel jLabel1;
    javax.swing.JLabel jLabel2;
    javax.swing.JButton recognize_button;
    javax.swing.JRadioButton recognize_radio;
    javax.swing.JButton record_button;
    javax.swing.JTextField vocala_text;
    // End of variables declaration//GEN-END:variables
}
